services:
  mysqldb:
    image: mysql:latest
    environment:
     - MYSQL_ROOT_PASSWORD=123456
     - MYSQL_DATABASE=bautistadb
    restart: always
    ports:
      - 3306:3306
  app:
    build: .
    depends_on:
      - mysqldb
    environment:
      - PASSWORD=123456
      - DBNAME=bautistadb
      - HOST=mysqldb
    ports:
      - 3000:3000
 



    



